apiVersion: v1
kind: Service
metadata:
  name: kstreams-count-service
  labels:
    app: kstreams-count
spec:
  clusterIP: None
  selector:
    app: kstreams-count
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kstreams-count
spec:
  serviceName: "kstreams-count-service"
  replicas: 2
  selector:
    matchLabels:
      app: kstreams-count
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kstreams-count
    spec:
      containers:
      - name: kstreams-count
        image: [registry name to be filled].azurecr.io/kstreams-count:latest
        env:
          - name: KAFKA_BROKER
            value: [to be filled]
        volumeMounts:
        - name: count-store
          mountPath: /data/count-store
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kstreams-count
            topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: count-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

